services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: .  # <-- Esto le dice a Portainer que use el Dockerfile de la raíz
    ports:
      - "8080:8080"
    environment:
      # Asegúrate de que el host coincida con el nombre del servicio de la base de datos ("db")
      - DB_URL=postgres://tu_usuario:tu_contraseña@db:5432/tu_base_datos
    depends_on:
      - postgres_db

volumes:
  postgres_data:
