// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_query.sql

package db

import (
	"context"
)

const changePassword = `-- name: ChangePassword :one
UPDATE account
SET
    password_hash = $2
WHERE account_id = $1
RETURNING username
`

type ChangePasswordParams struct {
	AccountID    int64  `json:"account_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) (string, error) {
	row := q.db.QueryRow(ctx, changePassword, arg.AccountID, arg.PasswordHash)
	var username string
	err := row.Scan(&username)
	return username, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO account (
    password_hash, mail, username, 
    board_skin, piece_skin, win_animation, avatar
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING account_id
`

type CreateAccountParams struct {
	PasswordHash string `json:"password_hash"`
	Mail         string `json:"mail"`
	Username     string `json:"username"`
	BoardSkin    int32  `json:"board_skin"`
	PieceSkin    int32  `json:"piece_skin"`
	WinAnimation int32  `json:"win_animation"`
	Avatar       int32  `json:"avatar"`
}

// Queries públicas desde endpoints
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.PasswordHash,
		arg.Mail,
		arg.Username,
		arg.BoardSkin,
		arg.PieceSkin,
		arg.WinAnimation,
		arg.Avatar,
	)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE account
SET
    mail = 'deleted_' || account_id::text,
    username = 'deleted_' || account_id::text,
    password_hash = '',
    is_deleted = TRUE
WHERE account_id = $1 AND is_deleted = FALSE
`

func (q *Queries) DeleteAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, accountID)
	return err
}

const deleteDevice = `-- name: DeleteDevice :one
DELETE FROM device
WHERE token = $1
RETURNING token
`

func (q *Queries) DeleteDevice(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, deleteDevice, token)
	var token_2 string
	err := row.Scan(&token_2)
	return token_2, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin, win_animation, avatar FROM account
WHERE account_id = $1 AND is_deleted = FALSE LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, accountID int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
		&i.WinAnimation,
		&i.Avatar,
	)
	return i, err
}

const getAccountByMail = `-- name: GetAccountByMail :one

SELECT account_id, password_hash FROM account
WHERE mail = $1 AND is_deleted = FALSE
`

type GetAccountByMailRow struct {
	AccountID    int64  `json:"account_id"`
	PasswordHash string `json:"password_hash"`
}

// Queries privadas que sólo se llaman desde dentro del sistema
func (q *Queries) GetAccountByMail(ctx context.Context, mail string) (GetAccountByMailRow, error) {
	row := q.db.QueryRow(ctx, getAccountByMail, mail)
	var i GetAccountByMailRow
	err := row.Scan(&i.AccountID, &i.PasswordHash)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT account_id, password_hash FROM account
WHERE username = $1 AND is_deleted = FALSE
`

type GetAccountByUsernameRow struct {
	AccountID    int64  `json:"account_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(&i.AccountID, &i.PasswordHash)
	return i, err
}

const getAccountIDByUsername = `-- name: GetAccountIDByUsername :one
SELECT account_id FROM account
WHERE username = $1 AND is_deleted = FALSE LIMIT 1
`

func (q *Queries) GetAccountIDByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountIDByUsername, username)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const getDevicesById = `-- name: GetDevicesById :many
SELECT token FROM device
WHERE user_id = $1
`

func (q *Queries) GetDevicesById(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getDevicesById, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordById = `-- name: GetPasswordById :one
SELECT password_hash FROM account
WHERE account_id = $1
`

func (q *Queries) GetPasswordById(ctx context.Context, accountID int64) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordById, accountID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getStats = `-- name: GetStats :one
SELECT level, xp, money
FROM account
WHERE account_id = $1 AND is_deleted = FALSE
`

type GetStatsRow struct {
	Level int32 `json:"level"`
	Xp    int32 `json:"xp"`
	Money int32 `json:"money"`
}

func (q *Queries) GetStats(ctx context.Context, accountID int64) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats, accountID)
	var i GetStatsRow
	err := row.Scan(&i.Level, &i.Xp, &i.Money)
	return i, err
}

const getUsernameByID = `-- name: GetUsernameByID :one
SELECT username FROM account
WHERE account_id = $1 AND is_deleted = FALSE LIMIT 1
`

func (q *Queries) GetUsernameByID(ctx context.Context, accountID int64) (string, error) {
	row := q.db.QueryRow(ctx, getUsernameByID, accountID)
	var username string
	err := row.Scan(&username)
	return username, err
}

const registerDevice = `-- name: RegisterDevice :one
INSERT INTO device (user_id, token)
VALUES ($1, $2)
RETURNING user_id
`

type RegisterDeviceParams struct {
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
}

func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (int64, error) {
	row := q.db.QueryRow(ctx, registerDevice, arg.UserID, arg.Token)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account
SET 
    username = COALESCE($2, username),
    board_skin = COALESCE($3, board_skin),
    piece_skin = COALESCE($4, piece_skin),
    win_animation = COALESCE($5, win_animation),
    avatar = COALESCE($6, avatar),
    mail = COALESCE($7, mail)
WHERE account_id = $1 AND is_deleted = FALSE
RETURNING account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin, win_animation, avatar
`

type UpdateAccountParams struct {
	AccountID    int64   `json:"account_id"`
	Username     *string `json:"username"`
	BoardSkin    *int32  `json:"board_skin"`
	PieceSkin    *int32  `json:"piece_skin"`
	WinAnimation *int32  `json:"win_animation"`
	Avatar       *int32  `json:"avatar"`
	Mail         *string `json:"mail"`
}

// solo cambia cosas qué se pueden cambiar por el user
// usa coalesce para solo actualizar los params que no
//
//	son null en la query
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.AccountID,
		arg.Username,
		arg.BoardSkin,
		arg.PieceSkin,
		arg.WinAnimation,
		arg.Avatar,
		arg.Mail,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
		&i.WinAnimation,
		&i.Avatar,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE account
SET
    password_hash = $2
WHERE account_id = $1 AND is_deleted = FALSE
`

type UpdatePasswordParams struct {
	AccountID    int64  `json:"account_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.AccountID, arg.PasswordHash)
	return err
}

const updateStats = `-- name: UpdateStats :exec
UPDATE account
SET
    level = $2,
    xp = $3,
    money = $4
WHERE account_id = $1 AND is_deleted = FALSE
`

type UpdateStatsParams struct {
	AccountID int64 `json:"account_id"`
	Level     int32 `json:"level"`
	Xp        int32 `json:"xp"`
	Money     int32 `json:"money"`
}

func (q *Queries) UpdateStats(ctx context.Context, arg UpdateStatsParams) error {
	_, err := q.db.Exec(ctx, updateStats,
		arg.AccountID,
		arg.Level,
		arg.Xp,
		arg.Money,
	)
	return err
}
