// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_query.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO account (
    password_hash, mail, username, 
    board_skin, piece_skin
)
VALUES ($1, $2, $3, $4, $5)
RETURNING account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin
`

type CreateAccountParams struct {
	PasswordHash string `json:"password_hash"`
	Mail         string `json:"mail"`
	Username     string `json:"username"`
	BoardSkin    int32  `json:"board_skin"`
	PieceSkin    int32  `json:"piece_skin"`
}

// Queries públicas desde endpoints
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.PasswordHash,
		arg.Mail,
		arg.Username,
		arg.BoardSkin,
		arg.PieceSkin,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE account
SET
    mail = 'deleted_' || account_id::text,
    username = 'deleted_' || account_id::text,
    password_hash = '',
    is_deleted = TRUE
WHERE account_id = $1 AND is_deleted = FALSE
`

func (q *Queries) DeleteAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, accountID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin FROM account
WHERE account_id = $1 AND is_deleted = FALSE LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, accountID int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}

const getAccountByMail = `-- name: GetAccountByMail :one

SELECT account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin FROM account
WHERE mail = $1 AND is_deleted = FALSE
`

// Queries privadas que sólo se llaman desde dentro del sistema
func (q *Queries) GetAccountByMail(ctx context.Context, mail string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByMail, mail)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin FROM account
WHERE username = $1 AND is_deleted = FALSE
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account
SET 
    username = COALESCE($2, username),
    board_skin = COALESCE($3, board_skin),
    piece_skin = COALESCE($4, piece_skin)
WHERE account_id = $1 AND is_deleted = FALSE
RETURNING account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin
`

type UpdateAccountParams struct {
	AccountID int64   `json:"account_id"`
	Username  *string `json:"username"`
	BoardSkin *int32  `json:"board_skin"`
	PieceSkin *int32  `json:"piece_skin"`
}

// solo cambia cosas qué se pueden cambiar por el user
// usa coalesce para solo actualizar los params que no
//
//	son null en la query
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.AccountID,
		arg.Username,
		arg.BoardSkin,
		arg.PieceSkin,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}

const updateMail = `-- name: UpdateMail :one
UPDATE account
SET
    mail = $2
WHERE account_id = $1 AND is_deleted = FALSE
RETURNING account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin
`

type UpdateMailParams struct {
	AccountID int64  `json:"account_id"`
	Mail      string `json:"mail"`
}

func (q *Queries) UpdateMail(ctx context.Context, arg UpdateMailParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateMail, arg.AccountID, arg.Mail)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE account
SET
    password_hash = $2
WHERE account_id = $1 AND is_deleted = FALSE
`

type UpdatePasswordParams struct {
	AccountID    int64  `json:"account_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.AccountID, arg.PasswordHash)
	return err
}

const updateStats = `-- name: UpdateStats :one
UPDATE account
SET
    level = $2,
    xp = $3,
    money = $4
WHERE account_id = $1 AND is_deleted = FALSE
RETURNING account_id, mail, username, password_hash, is_deleted, level, xp, money, board_skin, piece_skin
`

type UpdateStatsParams struct {
	AccountID int64 `json:"account_id"`
	Level     int32 `json:"level"`
	Xp        int32 `json:"xp"`
	Money     int32 `json:"money"`
}

func (q *Queries) UpdateStats(ctx context.Context, arg UpdateStatsParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateStats,
		arg.AccountID,
		arg.Level,
		arg.Xp,
		arg.Money,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.Mail,
		&i.Username,
		&i.PasswordHash,
		&i.IsDeleted,
		&i.Level,
		&i.Xp,
		&i.Money,
		&i.BoardSkin,
		&i.PieceSkin,
	)
	return i, err
}
