// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :exec
INSERT INTO "refresh_session" (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshSessionParams struct {
	AccountID int64              `json:"account_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, createRefreshSession, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	return err
}
