// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship_query.sql

package db

import (
	"context"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendship (
    user1_id, user2_id, accepted_1, accepted_2)
VALUES (
    $1, $2, $3, $4
)
RETURNING user1_id, user2_id, accepted_1, accepted_2
`

type CreateFriendshipParams struct {
	User1ID   int64 `json:"user1_id"`
	User2ID   int64 `json:"user2_id"`
	Accepted1 bool  `json:"accepted_1"`
	Accepted2 bool  `json:"accepted_2"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship,
		arg.User1ID,
		arg.User2ID,
		arg.Accepted1,
		arg.Accepted2,
	)
	var i Friendship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.Accepted1,
		&i.Accepted2,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendship 
WHERE ($1 = user1_id AND $2 = user2_id) OR ($1 = user2_id AND $2 = user1_id)
`

type DeleteFriendshipParams struct {
	User1ID int64 `json:"user1_id"`
	User2ID int64 `json:"user2_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.User1ID, arg.User2ID)
	return err
}

const getFiendship = `-- name: GetFiendship :one
SELECT user1_id, user2_id, accepted_1, accepted_2 FROM friendship 
WHERE ($1 = user1_id AND $2 = user2_id) OR ($1 = user2_id AND $2 = user1_id)
`

type GetFiendshipParams struct {
	User1ID int64 `json:"user1_id"`
	User2ID int64 `json:"user2_id"`
}

func (q *Queries) GetFiendship(ctx context.Context, arg GetFiendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFiendship, arg.User1ID, arg.User2ID)
	var i Friendship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.Accepted1,
		&i.Accepted2,
	)
	return i, err
}

const getUser1PendingRecievedFriendship = `-- name: GetUser1PendingRecievedFriendship :many
SELECT user2_id FROM friendship
WHERE ($1 = user1_id AND accepted_1 = FALSE AND accepted_2 = TRUE)
`

// ERES USER 1
func (q *Queries) GetUser1PendingRecievedFriendship(ctx context.Context, user1ID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUser1PendingRecievedFriendship, user1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user2_id int64
		if err := rows.Scan(&user2_id); err != nil {
			return nil, err
		}
		items = append(items, user2_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser1PendingSentFriendship = `-- name: GetUser1PendingSentFriendship :many
SELECT user2_id FROM friendship
WHERE ($1 = user1_id AND accepted_1 = TRUE AND accepted_2 = FALSE)
`

// ERES USER 1
func (q *Queries) GetUser1PendingSentFriendship(ctx context.Context, user1ID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUser1PendingSentFriendship, user1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user2_id int64
		if err := rows.Scan(&user2_id); err != nil {
			return nil, err
		}
		items = append(items, user2_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser2PendingRecievedFriendship = `-- name: GetUser2PendingRecievedFriendship :many
SELECT user1_id FROM friendship
WHERE ($1 = user2_id AND accepted_1 = TRUE AND accepted_2 = FALSE)
`

// ERES USER 2
func (q *Queries) GetUser2PendingRecievedFriendship(ctx context.Context, user2ID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUser2PendingRecievedFriendship, user2ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user1_id int64
		if err := rows.Scan(&user1_id); err != nil {
			return nil, err
		}
		items = append(items, user1_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser2PendingSentFriendship = `-- name: GetUser2PendingSentFriendship :many
SELECT user1_id FROM friendship
WHERE ($1 = user2_id AND accepted_1 = FALSE AND accepted_2 = TRUE)
`

// ERES USER 2
func (q *Queries) GetUser2PendingSentFriendship(ctx context.Context, user2ID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUser2PendingSentFriendship, user2ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user1_id int64
		if err := rows.Scan(&user1_id); err != nil {
			return nil, err
		}
		items = append(items, user1_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFriendships = `-- name: GetUserFriendships :many
SELECT user2_id FROM friendship
WHERE accepted_1 = TRUE AND accepted_2 = TRUE AND $1 = user1_id
`

func (q *Queries) GetUserFriendships(ctx context.Context, user1ID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserFriendships, user1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user2_id int64
		if err := rows.Scan(&user2_id); err != nil {
			return nil, err
		}
		items = append(items, user2_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFriendship = `-- name: SetFriendship :exec
UPDATE friendship
SET accepted_1 = TRUE, accepted_2 = TRUE
WHERE ($1 = user1_id AND $2 = user2_id) OR ($2 = user2_id AND $1 = user1_id)
`

type SetFriendshipParams struct {
	User1ID int64 `json:"user1_id"`
	User2ID int64 `json:"user2_id"`
}

func (q *Queries) SetFriendship(ctx context.Context, arg SetFriendshipParams) error {
	_, err := q.db.Exec(ctx, setFriendship, arg.User1ID, arg.User2ID)
	return err
}
