// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_query.sql

package db

import (
	"context"
)

const createItemOwner = `-- name: CreateItemOwner :one
INSERT INTO item_owner (
    user_id, item_id
)
VALUES (
    $1, $2
)
RETURNING user_id, item_id
`

type CreateItemOwnerParams struct {
	UserID int64 `json:"user_id"`
	ItemID int32 `json:"item_id"`
}

func (q *Queries) CreateItemOwner(ctx context.Context, arg CreateItemOwnerParams) (ItemOwner, error) {
	row := q.db.QueryRow(ctx, createItemOwner, arg.UserID, arg.ItemID)
	var i ItemOwner
	err := row.Scan(&i.UserID, &i.ItemID)
	return i, err
}

const getShopItem = `-- name: GetShopItem :one
SELECT item_id, price, level_requisite, item_type, is_default FROM shop_item
WHERE item_id = $1 LIMIT 1
`

func (q *Queries) GetShopItem(ctx context.Context, itemID int32) (ShopItem, error) {
	row := q.db.QueryRow(ctx, getShopItem, itemID)
	var i ShopItem
	err := row.Scan(
		&i.ItemID,
		&i.Price,
		&i.LevelRequisite,
		&i.ItemType,
		&i.IsDefault,
	)
	return i, err
}

const getUserItems = `-- name: GetUserItems :many
SELECT shop_item.item_id, price, level_requisite, item_type::ITEM_TYPE, is_default FROM item_owner 
JOIN shop_item ON shop_item.item_id = item_owner.item_id
WHERE user_id = $1
`

type GetUserItemsRow struct {
	ItemID         int32    `json:"item_id"`
	Price          int32    `json:"price"`
	LevelRequisite int32    `json:"level_requisite"`
	ItemType       ItemType `json:"item_type"`
	IsDefault      bool     `json:"is_default"`
}

func (q *Queries) GetUserItems(ctx context.Context, userID int64) ([]GetUserItemsRow, error) {
	rows, err := q.db.Query(ctx, getUserItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserItemsRow
	for rows.Next() {
		var i GetUserItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Price,
			&i.LevelRequisite,
			&i.ItemType,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
