// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_query.sql

package db

import (
	"context"
	"time"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO match (
    p1_id, p2_id, p1_elo, p2_elo, date, winner, termination, match_type, board,
	movement_history, time_base, time_increment 
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING match_id, p1_id, p2_id, p1_elo, p2_elo, date, winner, termination, match_type, board, movement_history, time_base, time_increment
`

type CreateMatchParams struct {
	P1ID            int64       `json:"p1_id"`
	P2ID            int64       `json:"p2_id"`
	P1Elo           int32       `json:"p1_elo"`
	P2Elo           int32       `json:"p2_elo"`
	Date            time.Time   `json:"date"`
	Winner          Winner      `json:"winner"`
	Termination     Termination `json:"termination"`
	MatchType       MatchType   `json:"match_type"`
	Board           BoardType   `json:"board"`
	MovementHistory string      `json:"movement_history"`
	TimeBase        int32       `json:"time_base"`
	TimeIncrement   int32       `json:"time_increment"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.P1ID,
		arg.P2ID,
		arg.P1Elo,
		arg.P2Elo,
		arg.Date,
		arg.Winner,
		arg.Termination,
		arg.MatchType,
		arg.Board,
		arg.MovementHistory,
		arg.TimeBase,
		arg.TimeIncrement,
	)
	var i Match
	err := row.Scan(
		&i.MatchID,
		&i.P1ID,
		&i.P2ID,
		&i.P1Elo,
		&i.P2Elo,
		&i.Date,
		&i.Winner,
		&i.Termination,
		&i.MatchType,
		&i.Board,
		&i.MovementHistory,
		&i.TimeBase,
		&i.TimeIncrement,
	)
	return i, err
}

const getMatch = `-- name: GetMatch :one
SELECT match_id, p1_id, p2_id, p1_elo, p2_elo, date, winner, termination, match_type, board, movement_history, time_base, time_increment FROM match
WHERE match_id = $1 LIMIT 1
`

func (q *Queries) GetMatch(ctx context.Context, matchID int64) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, matchID)
	var i Match
	err := row.Scan(
		&i.MatchID,
		&i.P1ID,
		&i.P2ID,
		&i.P1Elo,
		&i.P2Elo,
		&i.Date,
		&i.Winner,
		&i.Termination,
		&i.MatchType,
		&i.Board,
		&i.MovementHistory,
		&i.TimeBase,
		&i.TimeIncrement,
	)
	return i, err
}

const getPausedMatches = `-- name: GetPausedMatches :many
SELECT
    m.match_id,
    m.p1_id,
    m.p2_id,
    a1.username AS p1_username,
    a2.username AS p2_username,
    m.p1_elo,
    m.p2_elo,
    m.date,
    m.winner,
    m.termination,
    m.match_type,
    m.board,
    m.movement_history,
    m.time_base,
    m.time_increment
FROM match m
JOIN account a1 ON m.p1_id = a1.account_id
JOIN account a2 ON m.p2_id = a2.account_id
WHERE (m.p1_id = $1 OR m.p2_id = $1) AND m.termination = 'UNFINISHED'::termination
ORDER BY m.date DESC
`

type GetPausedMatchesRow struct {
	MatchID         int64       `json:"match_id"`
	P1ID            int64       `json:"p1_id"`
	P2ID            int64       `json:"p2_id"`
	P1Username      string      `json:"p1_username"`
	P2Username      string      `json:"p2_username"`
	P1Elo           int32       `json:"p1_elo"`
	P2Elo           int32       `json:"p2_elo"`
	Date            time.Time   `json:"date"`
	Winner          Winner      `json:"winner"`
	Termination     Termination `json:"termination"`
	MatchType       MatchType   `json:"match_type"`
	Board           BoardType   `json:"board"`
	MovementHistory string      `json:"movement_history"`
	TimeBase        int32       `json:"time_base"`
	TimeIncrement   int32       `json:"time_increment"`
}

func (q *Queries) GetPausedMatches(ctx context.Context, p1ID int64) ([]GetPausedMatchesRow, error) {
	rows, err := q.db.Query(ctx, getPausedMatches, p1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPausedMatchesRow
	for rows.Next() {
		var i GetPausedMatchesRow
		if err := rows.Scan(
			&i.MatchID,
			&i.P1ID,
			&i.P2ID,
			&i.P1Username,
			&i.P2Username,
			&i.P1Elo,
			&i.P2Elo,
			&i.Date,
			&i.Winner,
			&i.Termination,
			&i.MatchType,
			&i.Board,
			&i.MovementHistory,
			&i.TimeBase,
			&i.TimeIncrement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserHistory = `-- name: GetUserHistory :many
SELECT match_id, p1_id, p2_id, p1_elo, p2_elo, date, winner, termination, match_type, board, movement_history, time_base, time_increment FROM match
WHERE p1_id = $1 OR p2_id = $1
ORDER BY date DESC
`

func (q *Queries) GetUserHistory(ctx context.Context, p1ID int64) ([]Match, error) {
	rows, err := q.db.Query(ctx, getUserHistory, p1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.MatchID,
			&i.P1ID,
			&i.P2ID,
			&i.P1Elo,
			&i.P2Elo,
			&i.Date,
			&i.Winner,
			&i.Termination,
			&i.MatchType,
			&i.Board,
			&i.MovementHistory,
			&i.TimeBase,
			&i.TimeIncrement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE match
SET p1_id = $1, p2_id = $2, p1_elo = $3, p2_elo = $4, date = $5, winner = $6, 
    termination = $7, match_type = $8, board = $9, movement_history = $10, 
    time_base = $11, time_increment = $12
WHERE match_id = $13
RETURNING match_id, p1_id, p2_id, p1_elo, p2_elo, date, winner, termination, match_type, board, movement_history, time_base, time_increment
`

type UpdateMatchParams struct {
	P1ID            int64       `json:"p1_id"`
	P2ID            int64       `json:"p2_id"`
	P1Elo           int32       `json:"p1_elo"`
	P2Elo           int32       `json:"p2_elo"`
	Date            time.Time   `json:"date"`
	Winner          Winner      `json:"winner"`
	Termination     Termination `json:"termination"`
	MatchType       MatchType   `json:"match_type"`
	Board           BoardType   `json:"board"`
	MovementHistory string      `json:"movement_history"`
	TimeBase        int32       `json:"time_base"`
	TimeIncrement   int32       `json:"time_increment"`
	MatchID         int64       `json:"match_id"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.P1ID,
		arg.P2ID,
		arg.P1Elo,
		arg.P2Elo,
		arg.Date,
		arg.Winner,
		arg.Termination,
		arg.MatchType,
		arg.Board,
		arg.MovementHistory,
		arg.TimeBase,
		arg.TimeIncrement,
		arg.MatchID,
	)
	var i Match
	err := row.Scan(
		&i.MatchID,
		&i.P1ID,
		&i.P2ID,
		&i.P1Elo,
		&i.P2Elo,
		&i.Date,
		&i.Winner,
		&i.Termination,
		&i.MatchType,
		&i.Board,
		&i.MovementHistory,
		&i.TimeBase,
		&i.TimeIncrement,
	)
	return i, err
}
