// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Placeholder struct {
	ID   int32       `json:"id"`
	Data pgtype.Text `json:"data"`
}
