// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placeholder_query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaceholder = `-- name: CreatePlaceholder :one
INSERT INTO placeholder (data)
VALUES ($1)
ON CONFLICT (data) DO NOTHING
RETURNING id, data
`

func (q *Queries) CreatePlaceholder(ctx context.Context, data pgtype.Text) (Placeholder, error) {
	row := q.db.QueryRow(ctx, createPlaceholder, data)
	var i Placeholder
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}

const getPlaceholder = `-- name: GetPlaceholder :one
SELECT id, data FROM placeholder
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlaceholder(ctx context.Context, id int32) (Placeholder, error) {
	row := q.db.QueryRow(ctx, getPlaceholder, id)
	var i Placeholder
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}
