// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AcceptFriendship(ctx context.Context, arg AcceptFriendshipParams) error
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (string, error)
	CountSessionsByAccount(ctx context.Context, accountID int64) (int64, error)
	// Queries públicas desde endpoints
	CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error
	CreateItemOwner(ctx context.Context, arg CreateItemOwnerParams) error
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateRatings(ctx context.Context, userID int64) error
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error
	DeleteAccount(ctx context.Context, accountID int64) error
	DeleteDevice(ctx context.Context, token string) (string, error)
	DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error
	DeleteOldestSession(ctx context.Context, accountID int64) error
	DeleteRefreshSession(ctx context.Context, tokenHash string) error
	GetAccountByID(ctx context.Context, accountID int64) (Account, error)
	// Queries privadas que sólo se llaman desde dentro del sistema
	GetAccountByMail(ctx context.Context, mail string) (GetAccountByMailRow, error)
	GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error)
	GetAccountIDByUsername(ctx context.Context, username string) (int64, error)
	GetAllElos(ctx context.Context, userID int64) ([]Rating, error)
	GetBlitzElo(ctx context.Context, userID int64) (Rating, error)
	GetClassicElo(ctx context.Context, userID int64) (Rating, error)
	GetDevicesById(ctx context.Context, userID int64) ([]string, error)
	GetExtendedElo(ctx context.Context, userID int64) (Rating, error)
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error)
	GetMatch(ctx context.Context, matchID int64) (Match, error)
	GetPasswordById(ctx context.Context, accountID int64) (string, error)
	GetPausedMatches(ctx context.Context, p1ID int64) ([]GetPausedMatchesRow, error)
	GetRankById(ctx context.Context, arg GetRankByIdParams) (int64, error)
	GetRapidElo(ctx context.Context, userID int64) (Rating, error)
	GetRefreshSession(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetShopItem(ctx context.Context, itemID int32) (ShopItem, error)
	GetStats(ctx context.Context, accountID int64) (GetStatsRow, error)
	GetTopRankUsers(ctx context.Context, eloType EloType) ([]GetTopRankUsersRow, error)
	GetUserFriendships(ctx context.Context, user1ID int64) ([]GetUserFriendshipsRow, error)
	GetUserHistory(ctx context.Context, p1ID int64) ([]Match, error)
	GetUserItems(ctx context.Context, userID int64) ([]GetUserItemsRow, error)
	GetUserPendingReceivedFriendships(ctx context.Context, user1ID int64) ([]GetUserPendingReceivedFriendshipsRow, error)
	GetUserPendingReceivedFriendshipsCount(ctx context.Context, user1ID int64) ([]int64, error)
	GetUserPendingSentFriendships(ctx context.Context, user1ID int64) ([]GetUserPendingSentFriendshipsRow, error)
	GetUsernameByID(ctx context.Context, accountID int64) (string, error)
	ListShopItems(ctx context.Context) ([]ShopItem, error)
	RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (int64, error)
	// solo cambia cosas qué se pueden cambiar por el user
	// usa coalesce para solo actualizar los params que no
	//  son null en la query
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateRating(ctx context.Context, arg UpdateRatingParams) error
	UpdateStats(ctx context.Context, arg UpdateStatsParams) error
}

var _ Querier = (*Queries)(nil)
