// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rating_query.sql

package db

import (
	"context"
)

const createRatings = `-- name: CreateRatings :many
INSERT INTO rating (
    user_id, elo_type, value
)
VALUES 
(
    $1, elo_type.blitz,   $2
),
(
    $1, elo_type.bullet,  $3
),
(
    $1, elo_type.rapid,   $4
),
(
    $1, elo_type.classic, $5
)
RETURNING user_id, elo_type, value
`

type CreateRatingsParams struct {
	UserID  int64 `json:"user_id"`
	Value   int32 `json:"value"`
	Value_2 int32 `json:"value_2"`
	Value_3 int32 `json:"value_3"`
	Value_4 int32 `json:"value_4"`
}

func (q *Queries) CreateRatings(ctx context.Context, arg CreateRatingsParams) ([]Rating, error) {
	rows, err := q.db.Query(ctx, createRatings,
		arg.UserID,
		arg.Value,
		arg.Value_2,
		arg.Value_3,
		arg.Value_4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(&i.UserID, &i.EloType, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllElos = `-- name: GetAllElos :many
SELECT user_id, elo_type, value FROM rating
WHERE user_id = $1
`

func (q *Queries) GetAllElos(ctx context.Context, userID int64) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getAllElos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(&i.UserID, &i.EloType, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlitzElo = `-- name: GetBlitzElo :one
SELECT user_id, elo_type, value FROM rating
WHERE user_id = $1 AND elo_type = elo_type.blitz
`

func (q *Queries) GetBlitzElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getBlitzElo, userID)
	var i Rating
	err := row.Scan(&i.UserID, &i.EloType, &i.Value)
	return i, err
}

const getBulletElo = `-- name: GetBulletElo :one
SELECT user_id, elo_type, value FROM rating
WHERE user_id = $1 AND elo_type = elo_type.bullet
`

func (q *Queries) GetBulletElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getBulletElo, userID)
	var i Rating
	err := row.Scan(&i.UserID, &i.EloType, &i.Value)
	return i, err
}

const getClassicElo = `-- name: GetClassicElo :one
SELECT user_id, elo_type, value FROM rating
WHERE user_id = $1 AND elo_type = elo_type.classic
`

func (q *Queries) GetClassicElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getClassicElo, userID)
	var i Rating
	err := row.Scan(&i.UserID, &i.EloType, &i.Value)
	return i, err
}

const getRapidElo = `-- name: GetRapidElo :one
SELECT user_id, elo_type, value FROM rating
WHERE user_id = $1 AND elo_type = elo_type.rapid
`

func (q *Queries) GetRapidElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getRapidElo, userID)
	var i Rating
	err := row.Scan(&i.UserID, &i.EloType, &i.Value)
	return i, err
}

const updateRating = `-- name: UpdateRating :one
UPDATE rating
SET
    value = $3
WHERE user_id = $1 AND elo_type = $2
RETURNING user_id, elo_type, value
`

type UpdateRatingParams struct {
	UserID  int64   `json:"user_id"`
	EloType EloType `json:"elo_type"`
	Value   int32   `json:"value"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, updateRating, arg.UserID, arg.EloType, arg.Value)
	var i Rating
	err := row.Scan(&i.UserID, &i.EloType, &i.Value)
	return i, err
}
