// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rating_query.sql

package db

import (
	"context"
)

const createRatings = `-- name: CreateRatings :exec
INSERT INTO rating (user_id, elo_type)
VALUES 
    ($1, 'BLITZ'),
    ($1, 'EXTENDED'),
    ($1, 'RAPID'),
    ($1, 'CLASSIC')
`

func (q *Queries) CreateRatings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createRatings, userID)
	return err
}

const getAllElos = `-- name: GetAllElos :many
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1
`

func (q *Queries) GetAllElos(ctx context.Context, userID int64) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getAllElos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.UserID,
			&i.EloType,
			&i.Value,
			&i.Deviation,
			&i.Volatility,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlitzElo = `-- name: GetBlitzElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'BLITZ'::elo_type
`

func (q *Queries) GetBlitzElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getBlitzElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getClassicElo = `-- name: GetClassicElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'CLASSIC'::elo_type
`

func (q *Queries) GetClassicElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getClassicElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getExtendedElo = `-- name: GetExtendedElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'EXTENDED'::elo_type
`

func (q *Queries) GetExtendedElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getExtendedElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getRankById = `-- name: GetRankById :one
WITH user_score AS (
    SELECT r1.value 
    FROM rating r1
    WHERE r1.user_id = $2 AND r1.elo_type = $1
)
SELECT CAST(COUNT(*) + 1 AS BIGINT) AS rank
FROM rating r2
WHERE r2.elo_type = $1 
  AND (
      -- Contamos a los que tienen más puntos
      r2.value > (SELECT value FROM user_score)
      OR 
      -- O a los que tienen los mismos puntos pero menor ID (tu desempate)
      (r2.value = (SELECT value FROM user_score) AND r2.user_id < $2)
  )
`

type GetRankByIdParams struct {
	EloType EloType `json:"elo_type"`
	UserID  int64   `json:"user_id"`
}

func (q *Queries) GetRankById(ctx context.Context, arg GetRankByIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRankById, arg.EloType, arg.UserID)
	var rank int64
	err := row.Scan(&rank)
	return rank, err
}

const getRapidElo = `-- name: GetRapidElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'RAPID'::elo_type
`

func (q *Queries) GetRapidElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getRapidElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getTopRankUsers = `-- name: GetTopRankUsers :many
SELECT r.value, a.account_id, a.username, a.avatar
FROM rating r 
JOIN account a ON a.account_id = r.user_id
WHERE r.elo_type = $1
ORDER BY r.value DESC, r.user_id ASC LIMIT 100
`

type GetTopRankUsersRow struct {
	Value     int32  `json:"value"`
	AccountID int64  `json:"account_id"`
	Username  string `json:"username"`
	Avatar    int32  `json:"avatar"`
}

func (q *Queries) GetTopRankUsers(ctx context.Context, eloType EloType) ([]GetTopRankUsersRow, error) {
	rows, err := q.db.Query(ctx, getTopRankUsers, eloType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopRankUsersRow
	for rows.Next() {
		var i GetTopRankUsersRow
		if err := rows.Scan(
			&i.Value,
			&i.AccountID,
			&i.Username,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRating = `-- name: UpdateRating :exec
UPDATE rating
SET value = $3,
    deviation = $4,
    volatility = $5,
    last_updated_at = NOW()
WHERE user_id = $1 AND elo_type = $2
`

type UpdateRatingParams struct {
	UserID     int64   `json:"user_id"`
	EloType    EloType `json:"elo_type"`
	Value      int32   `json:"value"`
	Deviation  int32   `json:"deviation"`
	Volatility float64 `json:"volatility"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.Exec(ctx, updateRating,
		arg.UserID,
		arg.EloType,
		arg.Value,
		arg.Deviation,
		arg.Volatility,
	)
	return err
}
