// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rating_query.sql

package db

import (
	"context"
)

const createRatings = `-- name: CreateRatings :exec
INSERT INTO rating (user_id, elo_type)
VALUES 
    ($1, 'blitz'),
    ($1, 'extended'),
    ($1, 'rapid'),
    ($1, 'classic')
`

func (q *Queries) CreateRatings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createRatings, userID)
	return err
}

const getAllElos = `-- name: GetAllElos :many
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1
`

func (q *Queries) GetAllElos(ctx context.Context, userID int64) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getAllElos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.UserID,
			&i.EloType,
			&i.Value,
			&i.Deviation,
			&i.Volatility,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlitzElo = `-- name: GetBlitzElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'blitz'::elo_type
`

func (q *Queries) GetBlitzElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getBlitzElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getClassicElo = `-- name: GetClassicElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'classic'::elo_type
`

func (q *Queries) GetClassicElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getClassicElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getExtendedElo = `-- name: GetExtendedElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'extended'::elo_type
`

func (q *Queries) GetExtendedElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getExtendedElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const getRapidElo = `-- name: GetRapidElo :one
SELECT user_id, elo_type, value, deviation, volatility, last_updated_at FROM rating
WHERE user_id = $1 AND elo_type = 'rapid'::elo_type
`

func (q *Queries) GetRapidElo(ctx context.Context, userID int64) (Rating, error) {
	row := q.db.QueryRow(ctx, getRapidElo, userID)
	var i Rating
	err := row.Scan(
		&i.UserID,
		&i.EloType,
		&i.Value,
		&i.Deviation,
		&i.Volatility,
		&i.LastUpdatedAt,
	)
	return i, err
}

const updateRating = `-- name: UpdateRating :exec
UPDATE rating
SET value = $3,
    deviation = $4,
    volatility = $5,
    last_played_at = NOW()
WHERE user_id = $1 AND elo_type = $2
`

type UpdateRatingParams struct {
	UserID     int64   `json:"user_id"`
	EloType    EloType `json:"elo_type"`
	Value      int32   `json:"value"`
	Deviation  int32   `json:"deviation"`
	Volatility float64 `json:"volatility"`
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.Exec(ctx, updateRating,
		arg.UserID,
		arg.EloType,
		arg.Value,
		arg.Deviation,
		arg.Volatility,
	)
	return err
}
